package com.visitor.sets.test;

import com.visitor.card.types.Tome;
import com.visitor.game.parts.Game;
import com.visitor.helpers.CounterMap;

import java.util.UUID;

import static com.visitor.protocol.Types.Knowledge.*;

/**
 * Generated by card-lang
 */
public class TestTome extends Tome {

    public TestTome(Game game, UUID owner) {
        super(game, "Test Tome", "Study: Gain {U}{G}{P}{R}{Y}", owner, new CounterMap().add(GREEN, 9).add(PURPLE, 9).add(RED, 9).add(BLUE, 9).add(YELLOW, 9));
    }
}